#  Lab Introduction

Welcome to the lab *{lab_name}.*

In this lab you will be using OpenShift as a cluster admin.
Use the following details to log in.

* **Console:** link:{openshift_cluster_console_url}[window=_blank]
* **Username:** {openshift_cluster_admin_username}
* **Password:** {openshift_cluster_admin_password}

## Objectives

* Understand the lab setup
* Understand the application context

## Lab assets

//Before you begin, access your link:https://codeserver-codeserver-{openshift_cluster_user_name}.{openshift_cluster_ingress_domain}[code-server environment,window=_blank] and ensure you have access to the lab assets `ossm-labs`.

// Open a terminal (*`Terminal`* -> *`New Terminal`* from the menu) in the _code-server_ so that you can execute the commands during the labs.

You have a terminal on your right hand side and we have provided you with a repo assets (scripts) to be used throughout the lab.

Please clone the repository as shown below:

[source,shell,subs=attributes,role=execute]
----
git clone {virt_ossm_workspace_repo}/{virt_ossm_workspace_project}
----

List your cloned directory and see if all the assets are available:

[source,shell,subs=attributes,role=execute]
----
ls -la {virt_ossm_workspace_project}
----

You can go and inspect these resources in this repository at a later stage.

//Although for the labs the assets are made available you can additionally get and inspect these resources at a later stage from the link:https://github.com/redhat-gpte-devopsautomation/ossm-labs[ossm-labs,window=_blank] github repository.

## Openshift Cluster Environment

[IMPORTANT]
====
You will be using a *dedicated OpenShift cluster with OpenShift Virtualization, OpenShift Service Mesh and other components already installed*. In this lab you are going to explore and leverage these services, not going to install them.
====